### ISSUE TITLE
Corrections to mks_config.txt file

### ISSUE THREAD

**Issue by yogihybo** [majurca/MKS-TFT28-NEW-PICTURES#1]
Thanks for the excellent icon set - looks great on my MKS-TFT28

There are few things in the mks_config.txt file that result in the colors looking different to your sample images e.g. status background should be black but appears blue. My colours are as follows:

> cfg_background_color:0x000000
> cfg_title_color:0xFFFFFF
> cfg_state_background_color:0x000000
> cfg_state_text_color:0xFFFFFF
> cfg_filename_background_color:0x232323
> cfg_filename_color:0xFFFFFF
> cfg_printingstat_word_background_color:0x000000
> cfg_printingstat_word_color:0xFFFFFF
> cfg_BUTTON_3D_effects:0

Thanks again.

**Comment by majurca** [comment]
Hi yogihybo

You must modify with the following, and if you add the optional command you will have the access to the new optional buttons for bed leveling too.

cfg_background_color:0x000000
cfg_title_color:0xFFFFFF
cfg_state_background_color:0x800000
cfg_state_text_color:0xFFFFFF
cfg_filename_background_color:0xFF0015
cfg_filename_color:0xFFFFFF
cfg_printingstat_word_background_color:0xFF0015
cfg_printingstat_word_color:0xFFFFFF
cfg_BUTTON_3D_effects:0

moreitem_pic_cnt:6
moreitem_button1_cmd:G1 X5 Y5;
moreitem_button2_cmd:G1 X195 Y5;
moreitem_button3_cmd:G1 X195 Y195;
moreitem_button4_cmd:G1 X5 Y195;
moreitem_button5_cmd:G1 Z5;
moreitem_button6_cmd:G28 Z;
moreitem_button7_cmd:G28;
