### ISSUE TITLE
Turn off motors

### ISSUE THREAD

**Issue by tintinz** [majurca/MKS-TFT28-NEW-PICTURES#2]
Hey.
Love your icons. looks fantastic. the only I found as a "problem" was the icone for "turn of motors"
it says "return" and when you click on it nothing happening.

Thanks for your amazing art!

**Comment by majurca** [comment]
Hi tintinz

-What version of firmware are you using?
-What screen you have the problem?

Thanks

**Comment by tintinz** [comment]
I have the TFT28 display and firmware 1.1.4 
http://imgur.com/a/77Yuz

**Comment by majurca** [comment]
Hi tintinz

I just updated for firmware version 1.1.4
-new icon for Motor Off.
-new icons for communications at 57600 bauds.
-suppressed unused icons in 1.1.4 in SD sample

Verify in mks_config:
cfg_function_btn1_display:1
function_btn1_cmd:M84;

"Motor Off" only deactivate motors in idle status (see code M84 in Marlin gcodes)

Bye

**Comment by tintinz** [comment]
Awsome!
Thanks for the awsome work! :-)
