### ISSUE TITLE
Program used for .bin files

### ISSUE THREAD

**Issue by surdu** [majurca/MKS-TFT28-NEW-PICTURES#5]
Hello, 

Sorry to pose the question like this, but GitHub doesn't offer other forms of contacting:

What program did you use to create the bin files? Does InkScape produce the necessary bin files? Or if you used Image2LCD, what settings have you used for the file format?

Thank you!

**Comment by majurca** [comment]
Hi,

I use InkScape to create it, then save in png format. With Paint convert to bmp format for Image2LCD input.

With Image2LCD use:
Binary(*.bin)
Horizontal Scan
16-bit TrueColor.
320x240

Bye

**Comment by surdu** [comment]
Thank you!
