### ISSUE TITLE
Marlin (latest from the web) control over MKS TFT28 firmware version 2.0.0

### ISSUE THREAD

**Issue by Momboz52** [majurca/MKS-TFT28-NEW-PICTURES#6]
I am trying to control with an oscilloscope the output signals on the pins Dir and Step on a RAMPS 1.4 (Arduino + Shield) hardware and I can't understand why the "X"+ button under Move menu runs correctly and the "X-" doesn't. To better formulate it. Pressing the "X+" button on the TFT28 gives 8 Steps in the right Dir and pressing the "X-" button gives just 1 or 2 Steps in the right Dir.
Y axis reacts the same way.
Any feedback or view on this?
Many thanks.

**Comment by VisualGadget** [comment]
I have MKS SBASE (Smoothieware) and TFT32 with 2.0 firmware. All works well including X- movement.

**Comment by majurca** [comment]
For me all "X+" and "X-" works properly, anyway it is not related to TFT28 custom button pictures.
