### ISSUE TITLE
Please expand icon pack for 2.0 firmware.

### ISSUE THREAD

**Issue by VisualGadget** [majurca/MKS-TFT28-NEW-PICTURES#7]
Hello!

Recently I have updated TFT firmware to 2.0.0. There are few new icons. Please draw Leveling, Filament change and Continue the print. Your icon pack is the best looking one over there.

Regards,
Anton

**Comment by JDGon** [comment]
Hello,

I join the request. It's the best looking!

Thank you!

**Comment by majurca** [comment]
Hello

The work is finished. New version available.

I also created the icon "bmp_tool.bin" but I don't find were it is used.

Additionally I created a new icon "bmp_custom7.bin" that put the printer in "maintenance or clean position"

Enjoy it

**Comment by JDGon** [comment]
Thank you so much majurca!

**Comment by VisualGadget** [comment]
Thank you Majurca! Everything is shining.
